---

# Ref: https://www.xmodulo.com/disable-ipv6-linux.html

- name: "config-kernel-parameters: copy configuration file"
  become: True
  sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    reload: True
    state: "present"
  with_items: "{{ kernel_parameters }}"
  vars:
    kernel_parameters: 
      - name: "net.ipv6.conf.all.disable_ipv6"
        value: 1
      - name: "net.ipv6.conf.default.disable_ipv6"
        value: 1
      - name: "net.ipv6.conf.lo.disable_ipv6"
        value: 1

...