---
- hosts: all
  tasks:
    - name: "install general-packages"
      import_tasks: install-general-packages.yaml
      tags:
        - "install-general-packages"
    - name: "Install vs-code"
      import_tasks: install-vs-code.yaml
      tags:
        - "install-vs-code"
    - name: "Install Google Chrome"
      import_tasks: install-chrome.yaml
      tags:
        - "install-chrome"
    - name: "Install Brave browser"
      import_tasks: install-brave.yaml
      tags:
        - "install-brave"
    - name: "Install Surfshark Openvpn profiles"
      import_tasks: install-surfshark.yaml
      tags:
        - "install-surfshark"
    - name: "install cryptomator"
      import_tasks: install-cryptomator.yaml
      tags:
        - "install-cryptomator"
    - name: "install signal"
      import_tasks: install-signal.yaml
      tags:
        - "install-signal"
    - name: "config pulse audio"
      import_tasks: config-pulse-audio.yaml
      tags:
        - "config-pulse-audio"
    - name: "config kernel parameters"
      import_tasks: config-kernel-parameters.yaml
      tags:
        - "config-kernel-parameters"
    - name: "install docker ce and compose"
      import_tasks: install-docker.yaml
      tags:
        - "install-docker"    
    - name: "install flameshot"
      import_tasks: install-flameshot.yaml
      tags:
        - "install-flameshot" 
    - name: "install telegram"
      import_tasks: install-telegram.yaml
      tags:
        - "install-telegram" 
    - name: "install joplin"
      import_tasks: install-joplin.yaml
      tags:
        - "install-joplin" 
        
    # TODO: Add zsh terminal configuration [In Progress]    
    # - name: "install zsh and themes"
    #   import_tasks: install-zsh.yaml
    #   tags:
    #     - "install-zsh"  
...
