---
- hosts: all
  tasks:
    - name: "install general-packages"
      import_tasks: install-general-packages.yaml
      tags:
        - "install-general-packages"
    - name: "Install vs-code"
      import_tasks: install-vs-code.yaml
      tags:
        - "install-vs-code"
    - name: "Install Google Chrome"
      import_tasks: install-chrome.yaml
      tags:
        - "install-chrome"
    - name: "Install Surfshark Openvpn profiles"
      import_tasks: install-surfshark.yaml
      tags:
        - "install-surfshark"
    - name: "install cryptomator"
      import_tasks: install-cryptomator.yaml
      tags:
        - "install-cryptomator"
    - name: "Install Signal"
      import_tasks: install-signal.yaml
      tags:
        - "install-signal"
    - name: "config pulse audio"
      import_tasks: config-pulse-audio.yaml
      tags:
        - "config-pulse-audio"
    - name: "config kernel parameters"
      import_tasks: config-kernel-parameters.yaml
      tags:
        - "config-kernel-parameters"        
...
